<?php

namespace app\modules\system\models;

use app\components\ActiveRecord;
use dosamigos\translateable\TranslateableBehavior;
use Yii;

/**
 * This is the model class for table "{{%history}}".
 *
 * @property integer $id
 * @property integer $year
 * @property string $content
 * @property integer $status
 */
class History extends ActiveRecord
{

    const STATUS_PUBLISHED = 1;
    const STATUS_DRAFT = 0;

    public function behaviors()
    {
        return [
            'trans' => [
                'class' => TranslateableBehavior::className(),
                'translationAttributes' => ['content']
            ],
        ];
    }

    public function getTranslations()
    {
        return $this->hasMany(HistoryLang::className(), ['history_id' => 'id']);
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%history}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['year', 'content', 'status'], 'required'],
            [['year', 'status'], 'integer'],
            [['content'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('system', 'ID'),
            'year' => Yii::t('system', 'Year'),
            'content' => Yii::t('system', 'Content'),
            'status' => Yii::t('system', 'Status'),
        ];
    }


    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub

        // Видалення перекладу
        foreach ($this->getTranslations()->all() as $translations) {
            $translations->delete();
        }
    }
}
