<?php
/**
 * @package    oakcms
 * @author     Hryvinskyi Volodymyr <script@email.ua>
 * @copyright  Copyright (c) 2015 - 2017. Hryvinskyi Volodymyr
 * @version    0.0.1-alpha.0.4
 */

namespace app\components;

use app\modules\language\models\Language;
use Yii;
use yii\helpers\Url;
use yii\web\Application;

class BackendController extends CoreController
{

    public $error = null;
    public $_languages = NULL;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if(Yii::$app instanceof Application) {
            // Ініт мови сайту
            $this->_languages = Language::find()->where(['language_id' => Yii::$app->language])->asArray()->one();
            Yii::$app->session->set('_languages', $this->_languages);
        }
    }

    protected static function getDefaultLanguage($lang = false) {
        if($lang === false) {
            $lang = Language::findOne(Yii::$app->language);
        } else {
            $lang = Language::getLangByUrl($lang);
        }
        return $lang;
    }

    public function goBack($defaultUrl = null)
    {
        $backUrl = Yii::$app->getUser()->getReturnUrl($defaultUrl);

        if($backUrl == Url::to(['/admin/user/lock-screen'])) {
            return Yii::$app->getResponse()->redirect($defaultUrl);
        } else {
            return Yii::$app->getResponse()->redirect($backUrl);
        }
    }

    public function back()
    {
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function getReturnUrl($defaultUrl = null)
    {
        if(Yii::$app instanceof Application) {
            return Yii::$app->getSession()->get($this->module->id . '_return', $defaultUrl ? Url::to($defaultUrl) : Url::to('/admin/' . $this->module->id));
        }
        return null;
    }

    /**
     * Formats response depending on request type (ajax or not)
     * @param string $success
     * @param bool $back go back or refresh
     * @return mixed $result array if request is ajax.
     */
    public function formatResponse($success = '', $back = true)
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            if ($this->error) {
                return ['result' => 'error', 'error' => $this->error];
            } else {
                $response = ['result' => 'success'];
                if ($success) {
                    if (is_array($success)) {
                        $response = array_merge(['result' => 'success'], $success);
                    } else {
                        $response = array_merge(['result' => 'success'], ['message' => $success]);
                    }
                }
                return $response;
            }
        } else {
            if ($this->error) {
                $this->flash('error', $this->error);
            } else {
                if (is_array($success) && isset($success['message'])) {
                    $this->flash('success', $success['message']);
                } elseif (is_string($success)) {
                    $this->flash('success', $success);
                }
            }
            return $back ? $this->back() : $this->refresh();
        }
    }
}
