<?php
/**
 * Created by Vladimir Hryvinskyy.
 * Site: http://codice.in.ua/
 * Date: 11.10.2016
 * Project: kotsyubynsk
 * File name: CoreController.php
 */

namespace app\components;

class CoreController extends \yii\web\Controller
{
    public function afterAction($action, $result)
    {
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

    /**
     * Write in sessions alert messages
     * @param string $type error or success
     * @param string $message alert body
     */
    public function flash($type, $message)
    {
        if($session = \Yii::$app->getSession()) {
            $session->setFlash($type == 'error' ? 'danger' : $type, $message);
        }
    }
}
