<?php

/**
 * Created by Vladimir Hryvinskyy.
 * Site: http://codice.in.ua/
 * Date: 06.04.2016
 * Project: oakcms
 * File name: View.php
 */

namespace app\components;

use app\modules\admin\widgets\Html;
use yii\helpers\Url;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\AssetBundle;

class FrontendView extends CoreView
{
    public $bodyClass = [];
    public $adminPanel = true;

    public function isAdmin() {
        $rHostInfo = Url::home(true);
        if (!\Yii::$app->user->isGuest && strpos(\Yii::$app->request->absoluteUrl, $rHostInfo.'admin') !== false) {
            return true;
        } else {
            return false;
        }
    }


    public function init()
    {
        parent::init();
    }

    public function beforeRender($viewFile, $params)
    {
        return parent::beforeRender($viewFile, $params); // TODO: Change the autogenerated stub
    }

    /*public function registerJsFile($url, $options = [], $key = null)
    {
        $url = Yii::getAlias($url);
        $key = $key ?: $url;
        $depends = ArrayHelper::remove($options, 'depends', []);

        if (empty($depends)) {
            $position = ArrayHelper::remove($options, 'position', self::POS_HEAD);
            $this->jsFiles[$position][$key] = Html::jsFile($url, $options);
        } else {
            $this->getAssetManager()->bundles[$key] = new AssetBundle([
                'baseUrl' => '',
                'js' => [strncmp($url, '//', 2) === 0 ? $url : ltrim($url, '/')],
                'jsOptions' => $options,
                'depends' => (array) $depends,
            ]);
            $this->registerAssetBundle($key);
        }
    }*/
}
