<?php die; ?>
{
    "user_table": "#__ak_users",
    "dbdriver": "Mysqli",
    "dbhost": "127.0.0.1",
    "dbuser": "solo",
    "dbpass": "solo",
    "dbname": "solo",
    "prefix": "solo_",
    "timezone": "Europe\/Athens",
    "live_site": "http:\/\/solo.local.web\/",
    "session_timeout": "1440",
    "fs": {
        "driver": "file",
        "host": "127.0.0.1",
        "port": "21",
        "username": "nicholas",
        "password": "05vqms",
        "dir": "\/",
        "ssl": false,
        "passive": true,
        "directory": ""
    },
    "options": {
        "siteurl": "http:\/\/solo.local.web\/",
        "confwiz_upgrade": 1,
        "failure_timeout": "180",
        "failure_email_address": "",
        "failure_email_subject": "",
        "failure_email_body": "",
        "frontend_enable": true,
        "frontend_secret_word": "XgewmmJct8Sk8pNJ6pJC9RhfBoh0uAT2",
        "frontend_email_on_finish": true,
        "frontend_email_address": "",
        "frontend_email_subject": "",
        "frontend_email_body": "",
        "desktop_notifications": "1",
        "push_preference": "0",
        "push_apikey": "",
        "usesvnsource": false,
        "update_dlid": "",
        "minstability": "stable",
        "show_howtorestoremodal": 0
    },
    "useencryption": "1",
    "localtime": "1",
    "timezonetext": "T",
    "dateformat": "",
    "stats_enabled": "1",
    "driver": "Mysqli",
    "host": "localhost",
    "user": "solo",
    "pass": "solo",
    "name": "solo",
    "mail": {
        "online": true,
        "mailer": "mail",
        "mailfrom": "",
        "fromname": "",
        "smtpauth": false,
        "smtpsecure": "0",
        "smtpport": "1025",
        "smtpuser": "",
        "smtppass": "",
        "smtphost": "localhost"
    }
}