<?php
/**
 * @package    oakcms
 * @author     Hryvinskyi Volodymyr <script@email.ua>
 * @copyright  Copyright (c) 2015 - 2017. Hryvinskyi Volodymyr
 * @version    0.0.1-alpha.0.5
 */

namespace app\modules\language\models;

use Yii;

/**
 * This is the model class for table "{{%language_source}}".
 *
 * @property integer $id
 * @property string $category
 * @property string $message
 */
class LanguageSource extends \app\components\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%language_source}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['message'], 'string'],
            [['category'], 'string', 'max' => 32],
        ];
    }

    public function getLanguageTranslate()
    {
        return $this->hasMany(LanguageTranslate::className(), ['id' => 'id']);
    }

    public function afterDelete()
    {
        foreach ($this->getLanguageTranslate()->all() as $anguageTranslate) {
            $anguageTranslate->delete();
        }

        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('language', 'ID'),
            'category' => Yii::t('language', 'Category'),
            'message' => Yii::t('language', 'Message'),
        ];
    }
}
